"""add detail_rows table

Revision ID: 94e32f05f688
Revises: 55a813f6009e
Create Date: 2026-07-19 21:57:29.412217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e32f05f688'
down_revision: Union[str, Sequence[str], None] = '55a813f6009e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('sales_record_id', sa.Integer(), nullable=True),
    sa.Column('person', sa.String(), nullable=False),
    sa.Column('store', sa.String(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('bucket', sa.String(), nullable=True),
    sa.Column('rate', sa.Numeric(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('commission', sa.Numeric(), nullable=False),
    sa.Column('tag', sa.String(length=20), nullable=False),
    sa.Column('is_transferred', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'sales_record_id', name='uq_detail_month_sr')
    )
    with op.batch_alter_table('detail_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detail_rows_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_detail_rows_sales_record_id'), ['sales_record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detail_rows_sales_record_id'))
        batch_op.drop_index(batch_op.f('ix_detail_rows_month'))

    op.drop_table('detail_rows')
    # ### end Alembic commands ###
